import { defHttp } from '/@/utils/http/axios';
import { Modal } from 'ant-design-vue';

enum Api {
  /* list = '/sys/permission/list',
  save = '/sys/permission/add',
  edit = '/sys/permission/edit',
  delete = '/sys/permission/delete',
  deleteBatch = '/sys/permission/deleteBatch',
  ruleList = '/sys/permission/queryPermissionRule',
  ruleSave = '/sys/permission/addPermissionRule',
  ruleEdit = '/sys/permission/editPermissionRule',
  ruleDelete = '/sys/permission/deletePermissionRule',
  checkPermDuplication = '/sys/permission/checkPermDuplication', */

  list = '/sys/permission/list.json',
  save = '/sys/permission/add.json',
  edit = '/sys/permission/edit.json',
  delete = '/sys/permission/delete.json',
  deleteBatch = '/sys/permission/deleteBatch.json',
  ruleList = '/sys/permission/queryPermissionRule.json',
  ruleSave = '/sys/permission/addPermissionRule.json',
  ruleEdit = '/sys/permission/editPermissionRule.json',
  ruleDelete = '/sys/permission/deletePermissionRule.json',
  checkPermDuplication = '/sys/permission/checkPermDuplication.json',
}

/**
 * 列表接口
 * @param params
 */
export const list = (params) => {
  /* const result = {
    success: true,
    message: '',
    code: 0,
    result: [
      {
        id: '1438108176273760258',
        key: '1438108176273760258',
        title: 'Dashboard',
        parentId: '',
        name: 'Dashboard',
        perms: null,
        permsType: '1',
        icon: 'ion:grid-outline',
        component: 'layouts/default/index',
        componentName: null,
        url: '/dashboard',
        redirect: '/dashboard/analysis',
        sortNo: 1,
        menuType: 0,
        isLeaf: false,
        route: true,
        keepAlive: false,
        description: null,
        delFlag: 0,
        createBy: 'admin',
        createTime: '2021-09-15 19:51:23',
        updateBy: 'admin',
        updateTime: '2023-03-02 14:22:40',
        alwaysShow: false,
        hidden: true,
        status: '1',
        internalOrExternal: false,
        children: [
          {
            id: '9502685863ab87f0ad1134142788a385',
            key: '9502685863ab87f0ad1134142788a385',
            title: '首页',
            parentId: '1438108176273760258',
            name: '首页',
            perms: null,
            permsType: null,
            icon: 'ant-design:bank-filled',
            component: 'dashboard/analysis/index',
            componentName: null,
            url: '/dashboard/analysis',
            redirect: null,
            sortNo: 1,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: true,
            description: null,
            delFlag: 0,
            createBy: null,
            createTime: '2018-12-25 20:34:38',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:43:16',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
        ],
        leaf: false,
      },
      {
        id: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
        key: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
        title: '系统管理',
        parentId: '',
        name: '系统管理',
        perms: null,
        permsType: null,
        icon: 'ant-design:setting',
        component: 'layouts/RouteView',
        componentName: null,
        url: '/isystem',
        redirect: null,
        sortNo: 2,
        menuType: 0,
        isLeaf: false,
        route: true,
        keepAlive: false,
        description: null,
        delFlag: 0,
        createBy: null,
        createTime: '2018-12-25 20:34:38',
        updateBy: 'admin',
        updateTime: '2020-01-07 11:00:45',
        alwaysShow: false,
        hidden: false,
        status: null,
        internalOrExternal: false,
        children: [
          {
            id: '3f915b2769fc80648e92d04e84ca059d',
            key: '3f915b2769fc80648e92d04e84ca059d',
            title: '用户管理',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '用户管理',
            perms: null,
            permsType: null,
            icon: 'ant-design:user',
            component: 'system/user/index',
            componentName: null,
            url: '/system/user',
            redirect: null,
            sortNo: 1,
            menuType: 1,
            isLeaf: false,
            route: true,
            keepAlive: true,
            description: null,
            delFlag: 0,
            createBy: null,
            createTime: '2018-12-25 20:34:38',
            updateBy: 'sunjianlei',
            updateTime: '2021-05-08 09:57:31',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: [
              {
                id: '1214376304951664642',
                key: '1214376304951664642',
                title: '用户编辑',
                parentId: '3f915b2769fc80648e92d04e84ca059d',
                name: '用户编辑',
                perms: 'user:edit',
                permsType: '1',
                icon: null,
                component: '',
                componentName: null,
                url: '',
                redirect: null,
                sortNo: 1,
                menuType: 2,
                isLeaf: true,
                route: true,
                keepAlive: false,
                description: null,
                delFlag: 0,
                createBy: 'admin',
                createTime: '2020-01-07 10:40:47',
                updateBy: 'admin',
                updateTime: '2020-01-07 10:41:04',
                alwaysShow: false,
                hidden: false,
                status: '1',
                internalOrExternal: false,
                children: null,
                leaf: true,
              },
              {
                id: '1214462306546319362',
                key: '1214462306546319362',
                title: '新增用户',
                parentId: '3f915b2769fc80648e92d04e84ca059d',
                name: '新增用户',
                perms: 'user:add',
                permsType: '1',
                icon: null,
                component: '',
                componentName: null,
                url: '',
                redirect: null,
                sortNo: 1,
                menuType: 2,
                isLeaf: true,
                route: true,
                keepAlive: false,
                description: null,
                delFlag: 0,
                createBy: 'admin',
                createTime: '2020-01-07 16:22:32',
                updateBy: null,
                updateTime: null,
                alwaysShow: false,
                hidden: false,
                status: '1',
                internalOrExternal: false,
                children: null,
                leaf: true,
              },
              {
                id: '1a0811914300741f4e11838ff37a1d3a',
                key: '1a0811914300741f4e11838ff37a1d3a',
                title: '手机号禁用',
                parentId: '3f915b2769fc80648e92d04e84ca059d',
                name: '手机号禁用',
                perms: 'user:form:phone',
                permsType: '2',
                icon: null,
                component: '',
                componentName: null,
                url: '',
                redirect: null,
                sortNo: 1,
                menuType: 2,
                isLeaf: true,
                route: false,
                keepAlive: false,
                description: null,
                delFlag: 0,
                createBy: 'admin',
                createTime: '2019-05-11 17:19:30',
                updateBy: 'admin',
                updateTime: '2019-05-11 18:00:22',
                alwaysShow: false,
                hidden: false,
                status: '1',
                internalOrExternal: false,
                children: null,
                leaf: true,
              },
            ],
            leaf: false,
          },
          {
            id: '190c2b43bec6a5f7a4194a85db67d96a',
            key: '190c2b43bec6a5f7a4194a85db67d96a',
            title: '角色管理',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '角色管理',
            perms: null,
            permsType: null,
            icon: 'ant-design:solution',
            component: 'system/role/index',
            componentName: null,
            url: '/system/role',
            redirect: null,
            sortNo: 2,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: true,
            description: null,
            delFlag: 0,
            createBy: null,
            createTime: '2018-12-25 20:34:38',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:58:00',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1170592628746878978',
            key: '1170592628746878978',
            title: '菜单管理',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '菜单管理',
            perms: null,
            permsType: '1',
            icon: 'ant-design:menu-fold-outlined',
            component: 'system/menu/index',
            componentName: null,
            url: '/system/menu',
            redirect: null,
            sortNo: 3,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2019-09-08 15:00:05',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:40:01',
            alwaysShow: false,
            hidden: false,
            status: '1',
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '45c966826eeff4c99b8f8ebfe74511fc',
            key: '45c966826eeff4c99b8f8ebfe74511fc',
            title: '部门管理',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '部门管理',
            perms: null,
            permsType: null,
            icon: 'ant-design:team',
            component: 'system/depart/index',
            componentName: null,
            url: '/system/depart',
            redirect: null,
            sortNo: 3,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2019-01-29 18:47:40',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:58:13',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '5c2f42277948043026b7a14692456828',
            key: '5c2f42277948043026b7a14692456828',
            title: '我的部门',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '我的部门',
            perms: null,
            permsType: null,
            icon: 'ant-design:home-outlined',
            component: 'system/departUser/index',
            componentName: null,
            url: '/system/depart-user',
            redirect: null,
            sortNo: 4,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2019-04-17 15:12:24',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:58:41',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1438469604861403137',
            key: '1438469604861403137',
            title: '职务管理',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '职务管理',
            perms: null,
            permsType: '0',
            icon: 'ant-design:database-filled',
            component: 'system/position/index',
            componentName: null,
            url: '/system/position',
            redirect: null,
            sortNo: 5,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-16 19:47:33',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:58:22',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1438782851980210178',
            key: '1438782851980210178',
            title: '通知公告',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '通知公告',
            perms: null,
            permsType: '0',
            icon: 'ant-design:bell-outlined',
            component: 'system/notice/index',
            componentName: null,
            url: '/system/notice',
            redirect: null,
            sortNo: 8,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-17 16:32:17',
            updateBy: 'admin',
            updateTime: '2021-09-17 16:36:15',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1438782530717495298',
            key: '1438782530717495298',
            title: '分类字典',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '分类字典',
            perms: null,
            permsType: '0',
            icon: 'ant-design:group-outlined',
            component: 'system/category/index',
            componentName: null,
            url: '/system/category',
            redirect: null,
            sortNo: 9,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-17 16:31:01',
            updateBy: null,
            updateTime: null,
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1438782641187074050',
            key: '1438782641187074050',
            title: '数据字典',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '数据字典',
            perms: null,
            permsType: '0',
            icon: 'ant-design:hdd-twotone',
            component: 'system/dict/index',
            componentName: null,
            url: '/system/dict',
            redirect: null,
            sortNo: 10,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-17 16:31:27',
            updateBy: null,
            updateTime: null,
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1455735714507472898',
            key: '1455735714507472898',
            title: '通讯录',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '通讯录',
            perms: null,
            permsType: '0',
            icon: 'ant-design:book-outlined',
            component: 'system/address/index',
            componentName: null,
            url: '/address',
            redirect: null,
            sortNo: 10,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-11-03 11:16:55',
            updateBy: 'admin',
            updateTime: '2021-11-04 19:40:19',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1280350452934307841',
            key: '1280350452934307841',
            title: '租户管理',
            parentId: 'd7d6e2e4e2934f2c9385a623fd98c6f3',
            name: '租户管理',
            perms: null,
            permsType: '1',
            icon: 'ant-design:appstore-twotone',
            component: 'system/tenant/index',
            componentName: null,
            url: '/system/tenant',
            redirect: null,
            sortNo: 99,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2020-07-07 11:58:30',
            updateBy: 'admin',
            updateTime: '2021-09-17 15:40:41',
            alwaysShow: false,
            hidden: false,
            status: '1',
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1457678003102879745',
            key: '1457678003102879745',
            title: '系统编码规则',
            parentId: '1455100420297859074',
            name: '系统编码规则',
            perms: null,
            permsType: '0',
            icon: null,
            component: 'system/fillRule/index',
            componentName: null,
            url: '/system/fillrule',
            redirect: null,
            sortNo: 9,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-11-08 19:54:53',
            updateBy: 'admin',
            updateTime: '2021-11-18 10:49:40',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1458353686530232321',
            key: '1458353686530232321',
            title: '校验规则',
            parentId: '1455100420297859074',
            name: '校验规则',
            perms: null,
            permsType: '0',
            icon: null,
            component: 'system/checkRule/index',
            componentName: null,
            url: '/system/checkrule',
            redirect: null,
            sortNo: 15,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-11-10 16:39:48',
            updateBy: 'admin',
            updateTime: '2021-11-18 10:49:48',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1439488251473993730',
            key: '1439488251473993730',
            title: '定时任务',
            parentId: '1439398677984878593',
            name: '定时任务',
            perms: null,
            permsType: '0',
            icon: 'ant-design:history-outlined',
            component: 'monitor/quartz/index',
            componentName: null,
            url: '/monitor/quartz',
            redirect: null,
            sortNo: 1,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-19 15:15:18',
            updateBy: null,
            updateTime: null,
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1439511654494937090',
            key: '1439511654494937090',
            title: '数据源管理',
            parentId: '1439398677984878593',
            name: '数据源管理',
            perms: null,
            permsType: '0',
            icon: 'ant-design:hdd-filled',
            component: 'monitor/datasource/index',
            componentName: null,
            url: '/monitor/datasource',
            redirect: null,
            sortNo: 3,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-19 16:48:17',
            updateBy: null,
            updateTime: null,
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1439533711676973057',
            key: '1439533711676973057',
            title: '日志管理',
            parentId: '1439398677984878593',
            name: '日志管理',
            perms: null,
            permsType: '0',
            icon: 'ant-design:interaction-outlined',
            component: 'monitor/log/index',
            componentName: null,
            url: '/monitor/log',
            redirect: null,
            sortNo: 5,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-19 18:15:56',
            updateBy: 'admin',
            updateTime: '2021-09-19 18:16:56',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1443391584864358402',
            key: '1443391584864358402',
            title: '消息模板',
            parentId: '1443390062919208961',
            name: '消息模板',
            perms: null,
            permsType: '0',
            icon: null,
            component: 'system/message/template/index',
            componentName: null,
            url: '/message/template',
            redirect: null,
            sortNo: 2,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-30 09:45:45',
            updateBy: 'admin',
            updateTime: '2022-09-22 10:32:42',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
          {
            id: '1439542701152575489',
            key: '1439542701152575489',
            title: '我的消息',
            parentId: '1443390062919208961',
            name: '我的消息',
            perms: null,
            permsType: '0',
            icon: '',
            component: 'monitor/mynews/index',
            componentName: null,
            url: '/monitor/mynews',
            redirect: null,
            sortNo: 6,
            menuType: 1,
            isLeaf: true,
            route: true,
            keepAlive: false,
            description: null,
            delFlag: 0,
            createBy: 'admin',
            createTime: '2021-09-19 18:51:40',
            updateBy: 'admin',
            updateTime: '2022-09-22 10:33:10',
            alwaysShow: false,
            hidden: false,
            status: null,
            internalOrExternal: false,
            children: null,
            leaf: true,
          },
        ],
        leaf: false,
      },
    ],
    timestamp: 1677745127278,
  };
  return result.result; */
  return defHttp.get({ url: Api.list, params });
};

/**
 * 删除菜单
 */
export const deleteMenu = (params, handleSuccess) => {
  return defHttp.delete({ url: Api.delete, params }, { joinParamsToUrl: true }).then(() => {
    handleSuccess();
  });
};
/**
 * 批量删除菜单
 * @param params
 */
export const batchDeleteMenu = (params, handleSuccess) => {
  Modal.confirm({
    title: '确认删除',
    content: '是否删除选中数据',
    okText: '确认',
    cancelText: '取消',
    onOk: () => {
      return defHttp
        .delete({ url: Api.deleteBatch, data: params }, { joinParamsToUrl: true })
        .then(() => {
          handleSuccess();
        });
    },
  });
};
/**
 * 保存或者更新菜单
 * @param params
 */
export const saveOrUpdateMenu = (params, isUpdate) => {
  const url = isUpdate ? Api.edit : Api.save;
  return defHttp.post({ url: url, params });
};
/**
 * 菜单数据权限列表接口
 * @param params
 */
export const dataRuleList = (params) => defHttp.get({ url: Api.ruleList, params });
/**
 * 保存或者更新数据规则
 * @param params
 */
export const saveOrUpdateRule = (params, isUpdate) => {
  const url = isUpdate ? Api.ruleEdit : Api.ruleSave;
  return defHttp.post({ url: url, params });
};

/**
 * 删除数据权限
 */
export const deleteRule = (params, handleSuccess) => {
  return defHttp.delete({ url: Api.ruleDelete, params }, { joinParamsToUrl: true }).then(() => {
    handleSuccess();
  });
};
/**
 * 根据code获取字典数值
 * @param params
 */
export const ajaxGetDictItems = (params) =>
  defHttp.get({ url: `/sys/dict/getDictItems/${params.code}` });

/**
 * 唯一校验
 * @param params
 */
export const getCheckPermDuplication = (params) =>
  defHttp.get({ url: Api.checkPermDuplication, params }, { isTransformResponse: false });

/**
 * 校验菜单是否存在
 * @param model
 * @param schema
 * @param required
 */
export const checkPermDuplication = (model, schema, required?) => {
  return [
    {
      validator: (_, value) => {
        if (!value && required) {
          return Promise.reject(`请输入${schema.label}`);
        }
        return new Promise<void>((resolve, reject) => {
          getCheckPermDuplication({
            id: model.id,
            url: model.url,
            alwaysShow: model.alwaysShow,
          })
            .then((res) => {
              res.success ? resolve() : reject(res.message || '校验失败');
            })
            .catch((err) => {
              reject(err.message || '验证失败');
            });
        });
      },
    },
  ];
};
